language: cpp
compiler:
  - clang
os:
  - linux

env:
  global:
    - CODECOV_TOKEN=:fdb70632-da6f-49b5-83ca-74458a09059d

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - cmake-data
      - cmake
      - clang-3.8
      - lcov
script:
  - mkdir build && cd build
  - cmake .. && make
  - ./main-test

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}/build/
  - pwd
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"