language: cpp
compiler:
  - g++

os:
  - linux

install:
  - sudo pip install codecov
  #- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  #- sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90

env:
  global:
    - CODECOV_TOKEN=:fdb70632-da6f-49b5-83ca-74458a09059d

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - g++
script:
  - cmake . && make
  - ./main-test

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}/
  - pwd
  - cd CMakeFiles/Mison.dir/src
  - pwd
  - ls
  - codecov