language: cpp
compiler:
  - clang

os:
  - linux

install:
  - sudo pip install codecov

env:
  global:
    - CODECOV_TOKEN=:fdb70632-da6f-49b5-83ca-74458a09059d

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - cmake-data
      - cmake
      - g++
      - lcov
script:
  - cmake . && make
  - ./main-test

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}/
  - pwd
  - ./get_codecov.sh
  - codecov