language: cpp
compiler:
  - clang
os:
  - linux
install:
  - sudo pip install cpp-coveralls

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - cmake-data
      - cmake
      - clang-3.8
      - lcov
      - gcovr
script:
  - mkdir build && cd build
  - cmake .. && make
  - ./main-test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"